### PR TITLE
Add component-experts table (fixes #171)

### LINKED ISSUE #171: Add points of contact
In our stakeholder survey, several teams mentioned that we could make it easier for them to know who to ask questions of.

In particular, we would prefer to direct questions to [#SpiderMonkey](https://matrix.to/#/#spidermonkey:mozilla.org), but for situations like a needinfo in Bugzilla, it makes a lot of sense to direct a single person's attention to a bug.

We should add a section to spidermonkey.dev that lists components and SpiderMonkey members who volunteer to act as points of contect for those components.

There is a similar, out-dated [page on the Wiki](https://wiki.mozilla.org/JavaScript:Hackers) that we could use for inspiration.

### PR DESCRIPTION
**Pull request by bthrall**
Is the list of components complete? Should we remove any?

Feel free to add any volunteer names.

### CODE REVIEW

**Comment by bthrall** [comment]
I'm really not liking the table styling, but I'm also not familiar enough with Jekyll to fix it easily

**Comment by mgaudet** [comment]
Then netlify preview being broken is a bit wierd... I wonder if we should try try force-pushing again on Monday to see if they can get unstuck

**Comment by bthrall** [comment]
I created #176 to cover fixing the netlify preview being broken

**Review by mgaudet — APPROVED** [review]
LGTM

**Pull request merged**
