### PR TITLE
Add social media in footer

### PR DESCRIPTION
**Pull request by allstarschh**

### CODE REVIEW

**Comment by codehag** [comment]
mind if I merge this?

**Comment by allstarschh** [comment]
@codehag Give me one more day to try this :P 
So I am trying the following things, can you help to answer that?
1. Finding an (svg) icon for matrix chat.
2. "content links and copyright on the right" What are the content links, and where can I find the copyright?
3. "We also likely want to add links to the blog, contributing, and also maybe a code of conduct." We already have the blog link on top, do we still need that in footer?

**Comment by codehag** [comment]
Sounds good!

**Comment by codehag** [comment]
for 2: we can skip the copy right for now, content links are: "blog" "docs" "contribute" "etc" (same as top). It's weird but common

for 3: yep!

**Pull request closed without merging**
