### PR TITLE
Text spacing improvement

### PR DESCRIPTION
**Pull request by willyelm**
Updating text spacing to follow WCAG 2.2 spacing guidelines. In this case, using double(32px) the font-size(16px) for following paragraphs.

### CODE REVIEW

**Comment by mgaudet** [comment]
So looking at the deploy preview [here](https://deploy-preview-155--spidermonkey-dev.netlify.app/blog/2023/11/27/newsletter-firefox-118-121) it still seems very large (preview is left).

Screenshot 2024-01-24 at 3 18 11 PM

would love it if the spacing looked more like github.

**Comment by arai-a** [comment]
I wonder if the spacing around a list isn't the target of "Spacing following paragraphs" definition.

Actually, the spec itself doesn't use "2 times the font size" spacing for the list that defines the spacing:
https://www.w3.org/TR/WCAG22/#text-spacing

"2 times the font size" or more spacing is applied to heading (`margin-top: 3rem`), but not for `<p>`.

maybe we should follow what the spec css does, by applying the spacing only to heading's margin-top?

**Comment by willyelm** [comment]
My initial intention was to keep changes to the minimum while using a good set of guidelines.

I like the approach of using the W3 site spec CSS as our reference as It makes me feel more comfortable, after considering your suggestions @arai-a, @mgaudet. I made some changes and I think we got better results. 

Let me know what you think.

**Comment by arai-a** [comment]
thanks!
looks good to me :)

**Review by mgaudet — APPROVED** [review]
Oh that looks so much better to me.

**Pull request merged**
